server:
  port: 8001

mybatis:
  type-aliases-package: com.chao.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: SPRINGCLOUD-PROVIDER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liu?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: 3925096

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

info:
  app.name: LiuChao Apps
  app.description: I'm learning SpringCloud.